phonesort: phonefind.c
	gcc -std=c17 -Wall -Wextra -O2 -o phonefind phonefind.c

run:
	./phonefind contacts.csv john
	./phonefind contacts.csv ja
	./phonefind contacts.csv 485
	./phonefind contacts.csv Garcia
	./phonefind contacts.csv xyz

clean:
	rm -f phonesort
